language: python
python: 2.7
install:
  - pip install -qq flake8 pytest pytest-cov tox
  - python setup.py install
script:
  - flake8 --version
  - flake8 --ignore=E501 pingo
  - py.test pingo -vrsx --cov pingo
after_success:
  - pip install -qq coveralls
  - coveralls
